spring:
  datasource:
    url: jdbc:mysql://localhost:3306/performance_example
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

